CONFIG_ZMK_KEYBOARD_NAME="Corne"

# Sin OLED / pantalla
CONFIG_ZMK_DISPLAY=n

# RGB / Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y

# Batería
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# Bluetooth compatibility
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000